CREATE TABLE PRODUCT(
  PRODUCT_ID BIGSERIAL PRIMARY KEY,
  TITLE VARCHAR,
  PRICE DOUBLE,
  DESCRIPTION VARCHAR,
  CATEGORY VARCHAR(64),
  IMAGE VARCHAR,
  RATE DOUBLE,
  COUNTS INTEGER
);

CREATE INDEX IDX_CATEGORY ON PRODUCT(CATEGORY);
CREATE INDEX IDX_PRICE ON PRODUCT(PRICE);
